---
apiVersion: aquasecurity.github.io/v1alpha1
kind: ClusterComplianceReport
metadata:
  name: nsa
spec:
  specKind: compliance
  name: nsa
  description: National Security Agency - Kubernetes Hardening Guidance
  version: "1.0"
  cron: "* * * * *"
  controls:
    - name: Non-root containers
      description: ''
      id: '1.0'
      resources:
        - Workload
      mapping:
        scanner: config-audit
        checks:
          - id: KSV012
    - name: Immutable container file systems
      description: ''
      id: '1.1'
      resources:
        - Workload
      mapping:
        scanner: config-audit
        checks:
          - id: KSV014
    - name: Preventing privileged containers
      description: ''
      id: '1.2'
      resources:
        - Workload
      mapping:
        scanner: config-audit
        checks:
          - id: KSV017
    - name: share host process namespaces
      description: ''
      id: '1.3'
      resources:
        - Workload
      mapping:
        scanner: config-audit
        checks:
          - id: KSV008
    - name: share host process namespaces.
      description: ''
      id: '1.4'
      resources:
        - Workload
      mapping:
        scanner: config-audit
        checks:
          - id: KSV009
    - name: use the host network
      id: '1.5'
      resources:
        - Workload
      mapping:
        scanner: config-audit
        checks:
          - id: KSV010
    - name: applications can run with root privileges or with root group membership
      description: ''
      id: '1.6'
      resources:
        - Workload
      mapping:
        scanner: config-audit
        checks:
          - id: KSV029
    - name: Restricts escalation to root privileges.
      description: ''
      id: '1.7'
      resources:
        - Workload
      mapping:
        scanner: config-audit
        checks:
          - id: KSV001
    - name: Sets the SELinux context of the container.
      description: ''
      id: '1.8'
      resources:
        - Workload
      mapping:
        scanner: config-audit
        checks:
          - id: KSV002
    - name: Restrict a container's access to resources with AppArmor
      description: ''
      id: '1.9'
      resources:
        - Workload
      mapping:
        scanner: config-audit
        checks:
          - id: KSV030
    - name: Sets the seccomp profile used to sandbox containers.
      description: ''
      id: '1.10'
      resources:
        - Workload
      mapping:
        scanner: config-audit
        checks:
          - id: KSV036
    - name: Protecting Pod service account tokens
      description: ''
      id: '1.11'
      resources:
        - Workload
      mapping:
        scanner: config-audit
        checks:
          - id: KSV037
    - name: Namespace kube-system should should not be used by users
      description: ''
      id: '1.12'
      resources:
        - Workload
      mapping:
        scanner: config-audit
        checks:
          - id: KSV038
    - name: pod and/or namespace Selectors usage
      description: ''
      id: '2.0'
      resources:
        - Workload
      mapping:
        scanner: config-audit
        checks:
          - id: KSV038
    - name: Use CNI plugin that supports NetworkPolicy API
      description: ''
      id: '3.0'
      resources:
        - Node
      mapping:
        scanner: kube-bench
        checks:
          - id: 5.3.1
    - name: Use a default policy to deny all ingress and egress traffic
      description: ''
      id: '3.1'
      resources:
        - NetworkPolicy
      mapping:
        scanner: kube-bench
        checks:
          - id: "<check need to be added>"
    - name: Use LimitRange and ResourceQuota policies to limit resources
      description: ''
      id: '4.0'
      resources:
        - LimitRange
      mapping:
        scanner: kube-bench
        checks:
          - id: "<check need to be added>"
    - name: Control plan disable insecure port
      description: ''
      id: '5.0'
      resources:
        - Node
      mapping:
        scanner: kube-bench
        checks:
          - id: 1.2.19
    - name: Encrypt etcd communication
      description: ''
      id: '5.1'
      resources:
        - Node
      mapping:
        scanner: kube-bench
        checks:
          - id: '2.1'
    - name: Ensure kube config file permission
      description: ''
      id: '6.0'
      resources:
        - Node
      mapping:
        scanner: kube-bench
        checks:
          - id: 4.1.3
          - id: 4.1.4
    - name: Check that encryption resource has been set
      description: ''
      id: '6.1'
      resources:
        - EncryptionConfiguration
      mapping:
        scanner: kube-bench
        checks:
          - id: 1.2.31"
          - id: 1.2.32"
    - name: Check encryption provider
      description: ''
      id: '6.2'
      resources:
        - Node
      mapping:
        scanner: kube-bench
        checks:
          - id: 1.2.3
    - name: Make sure anonymous-auth is unset
      description: ''
      id: '7.0'
      resources:
        - Node
      mapping:
        scanner: kube-bench
        checks:
          - id: 1.2.1
    - name: Make sure -authorization-mode=RBAC
      description: ''
      id: '7.1'
      resources:
        - Node
      mapping:
        scanner: kube-bench
        checks:
          - id: 1.2.7
          - id: 1.2.8
    - name: Audit policy is configure
      description: ''
      id: '8.0'
      resources:
        - Node
      mapping:
        scanner: kube-bench
        checks:
          - id: 3.2.1
    - name: Audit log path is configure
      description: ''
      id: '8.1'
      resources:
        - Node
      mapping:
        scanner: kube-bench
        checks:
          - id: 1.2.22
    - name: Audit log aging
      description: ''
      id: '8.2'
      resources:
        - Node
      mapping:
        scanner: kube-bench
        checks:
          - id: 1.2.23
    - name: service mesh is configure
      description: ''
      id: '9.0'
      resources:
        - Node
      mapping:
        scanner: kube-bench
        checks:
          - id: "<check need to be added>"