blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/aquasecurity/starboard/discussions/new?category_id=18526499
    about: Share ideas for new features
  - name: Ask a question
    url: https://github.com/aquasecurity/starboard/discussions/new?category_id=18526498
    about: Ask questions and discuss with other community members
