apiVersion: v2
name: starboard-operator
description: Keeps security report resources updated
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.10.8

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 0.15.8

# kubeVersion: A SemVer range of compatible Kubernetes versions (optional)

keywords:
  - aquasecurity
  - starboard
  - trivy
# home: https://github.com/aquasecurity/starboard
sources:
  - https://github.com/aquasecurity/starboard
# maintainers: # (optional)
#   - name: The maintainers name (required for each maintainer)
#     email: The maintainers email (optional for each maintainer)
#     url: A URL for the maintainer (optional for each maintainer)
# icon: A URL to an SVG or PNG image to be used as an icon (optional).
# annotations:
#   example: A list of annotations keyed by name (optional).
