name: Publish to Amazon ECR
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag to publish'
        required: true

jobs:
  deploy:
    name: Publish to Amazon ECR
    runs-on: ubuntu-18.04
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - run: |
          docker pull aquasec/starboard:${{ github.event.inputs.tag }}
          docker tag aquasec/starboard:${{ github.event.inputs.tag }} public.ecr.aws/aquasecurity/starboard:${{ github.event.inputs.tag }}
          docker push public.ecr.aws/aquasecurity/starboard:${{ github.event.inputs.tag }}
